### PR TITLE
[system-loaders] System Element (+ Element Loader) Implementation

### PR DESCRIPTION
**Pull request by 0exp**
### Realized: definition and instantiation

- `init` process;
- `start` process;
- `stop` process;
- callbacks (`before` and `after` for each process type);
- loader definition DSL;
- loader instantitation abstractions;
- `Siege::System` definition DSL;
- `Siege::System` instantiation;

```ruby
class SimpleLoader < Siege::System::Loader
  init {}
  start {}
  stop {}

  before_init { }
  after_init {}
  before_start {}
  after_start {}
  before_stop {}
  after_stop {}
end
```

```ruby
class SimpleSystem < Siege::System
  element(:database) do
    init {}
    start {}
    stop {}
    before_init {}
    before_start {}
    before_stop {}
    after_init {}
    after_start {}
    after_stop {}
  end

  element(:logging, loader: LoggingLoader) # explicit loader deifnition
end
```

```ruby
app = SimpleSystem.create_instance # => #<SimpleSystem:0x00007f81884d7310>
```

---

### Coming soon:

- customizable setting options (powered by `qonfig`);
- usage of loaders inside another loaders (welcome to `Visitor`s);

### CODE REVIEW

**Review by akxcv — COMMENTED** [review]
Beautiful!

Does this support code reloading?

**Comment by 0exp** [comment]
@akxcv i think "YES"

**Comment by akxcv** [comment]
> @akxcv i think "YES"

I don't see it in the API... Could you provide an example, please?

**Comment by 0exp** [comment]
@akxcv i'm in progress :)

**Comment by 0exp** [comment]
go to master

**Pull request merged**
